import tensorflow as tf
actor_fc_layers=(60, 45)
actor_output_fc_layers=(15,)
actor_lstm_size=(6,)
actor_learning_rate=3e-4
critic_obs_fc_layers=(30,)
critic_action_fc_layers=(30,)
critic_joint_fc_layers=(45,)
critic_output_fc_layers=(15,)
critic_lstm_size=(6,)
critic_learning_rate=3e-4
alpha_learning_rate=3e-4
target_update_tau=0.05
target_update_period=1
td_errors_loss_fn=tf.math.squared_difference
gamma=0.99
reward_scale_factor=0.1
gradient_clipping=None
debug_summaries=False
summarize_grads_and_vars=False
replay_buffer_capacity=100000
initial_collect_episodes=200
collect_episodes_per_iteration=1
use_tf_functions=True
summaries_flush_secs=10
num_eval_episodes=10
observations_allowlist='position'
eval_metrics_callback=None
batch_size=64
train_sequence_length=10
num_iterations=1000
train_steps_per_iteration=200
eval_interval=200
log_interval=200
summary_interval=1000
global_step = tf.compat.v1.train.get_or_create_global_step()